language: python

cache:
  directories:
    - $HOME/.cache/pip
    - $HOME/Library/Caches/Homebrew
    - $HOME/HomebrewLocal
    - $HOME/.ccache
    - /Library/Caches/Homebrew
    - $HOME/Library/Caches/pip/wheels
    - /Library/Caches/pip/wheels

matrix:
  include:
    - os: osx
      osx_image: xcode7.3
      language: generic
      env:
        - PY_VERSION=3
        - PY_VERSION_=3.5
        - MAKEFLAGS=-j8
    - os: osx
      osx_image: xcode7.3
      language: generic
      env:
        - PY_VERSION=3
        - PY_VERSION_=3.6
        - MAKEFLAGS=-j8
    - os: osx
      osx_image: xcode7.3
      language: generic
      env:
        - PY_VERSION=3
        - PY_VERSION_=3.7
        - MAKEFLAGS=-j8
    - os: osx
      osx_image: xcode7.3
      language: generic
      env:
        - PY_VERSION=3
        - PY_VERSION_=3.8
        - MAKEFLAGS=-j8

before_install:
  - export PATH=/usr/lib/ccache:$PATH
  - source buildconfig/ci/travis/.travis_osx_before_install.sh

install:
  - "python buildconfig/ci/travis/.travis_osx_upload_whl.py --write-config"
  - $(set | grep PYPI_ | python -c "import sys;print('\n'.join(['unset %s' % l.split('=')[0] for l in sys.stdin.readlines() if l.startswith('PYPI')]))")
  - source buildconfig/ci/travis/.travis_osx.sh
  - "$PIP_CMD install --upgrade pip"
  - "$PIP_CMD install --upgrade numpy"
  - $PIP_CMD install delocate twine
  - source buildconfig/ci/travis/.travis_osx_install.sh

env:
  global:
    - SDL_VIDEODRIVER=dummy
    - SDL_AUDIODRIVER=disk
script:
  - $PYTHON_EXE -m pygame.tests.__main__ --exclude opengl --time_out 300

after_success:
  - source buildconfig/ci/travis/.travis_osx_after_success.sh

after_script:
  - rm -f .travis_tmp

deploy:
  - provider: releases
    api_key: $GH_API_TOKEN
    file_glob: true
    file:
      - dist/*.whl
    skip_cleanup: true
    draft: true
    on:
      all_branches: true
      tag: true
